# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Set')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Set')
    _Set = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Set', [dirname(__file__)])
        except ImportError:
            import _Set
            return _Set
        try:
            _mod = imp.load_module('_Set', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Set = swig_import_helper()
    del swig_import_helper
else:
    import _Set
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class Node(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Node, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Node, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nodeData"] = _Set.Node_nodeData_set
    __swig_getmethods__["nodeData"] = _Set.Node_nodeData_get
    if _newclass:
        nodeData = _swig_property(_Set.Node_nodeData_get, _Set.Node_nodeData_set)
    __swig_setmethods__["left"] = _Set.Node_left_set
    __swig_getmethods__["left"] = _Set.Node_left_get
    if _newclass:
        left = _swig_property(_Set.Node_left_get, _Set.Node_left_set)
    __swig_setmethods__["right"] = _Set.Node_right_set
    __swig_getmethods__["right"] = _Set.Node_right_get
    if _newclass:
        right = _swig_property(_Set.Node_right_get, _Set.Node_right_set)

    def __init__(self):
        this = _Set.new_Node()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Set.delete_Node
    __del__ = lambda self: None
Node_swigregister = _Set.Node_swigregister
Node_swigregister(Node)

class Set(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Set, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Set, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _Set.new_Set()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Set.delete_Set
    __del__ = lambda self: None

    def put(self, x: 'int') -> "void":
        return _Set.Set_put(self, x)

    def find(self, x: 'int') -> "void":
        return _Set.Set_find(self, x)

    def max_elem(self, n: 'Node') -> "void":
        return _Set.Set_max_elem(self, n)

    def min_elem(self, n: 'Node') -> "void":
        return _Set.Set_min_elem(self, n)

    def display(self) -> "void":
        return _Set.Set_display(self)
Set_swigregister = _Set.Set_swigregister
Set_swigregister(Set)

# This file is compatible with both classic and new-style classes.


