# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_sortinglib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_sortinglib')
    _sortinglib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sortinglib', [dirname(__file__)])
        except ImportError:
            import _sortinglib
            return _sortinglib
        try:
            _mod = imp.load_module('_sortinglib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _sortinglib = swig_import_helper()
    del swig_import_helper
else:
    import _sortinglib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _sortinglib.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self) -> "PyObject *":
        return _sortinglib.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _sortinglib.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _sortinglib.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _sortinglib.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _sortinglib.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _sortinglib.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _sortinglib.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _sortinglib.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _sortinglib.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _sortinglib.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _sortinglib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _sortinglib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _sortinglib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _sortinglib.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _sortinglib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _sortinglib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _sortinglib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _sortinglib.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _sortinglib.IntVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _sortinglib.IntVector___bool__(self)

    def __len__(self) -> "std::vector< int >::size_type":
        return _sortinglib.IntVector___len__(self)

    def __getslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> "std::vector< int,std::allocator< int > > *":
        return _sortinglib.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _sortinglib.IntVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< int >::difference_type', j: 'std::vector< int >::difference_type') -> "void":
        return _sortinglib.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _sortinglib.IntVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< int >::value_type const &":
        return _sortinglib.IntVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _sortinglib.IntVector___setitem__(self, *args)

    def pop(self) -> "std::vector< int >::value_type":
        return _sortinglib.IntVector_pop(self)

    def append(self, x: 'std::vector< int >::value_type const &') -> "void":
        return _sortinglib.IntVector_append(self, x)

    def empty(self) -> "bool":
        return _sortinglib.IntVector_empty(self)

    def size(self) -> "std::vector< int >::size_type":
        return _sortinglib.IntVector_size(self)

    def swap(self, v: 'IntVector') -> "void":
        return _sortinglib.IntVector_swap(self, v)

    def begin(self) -> "std::vector< int >::iterator":
        return _sortinglib.IntVector_begin(self)

    def end(self) -> "std::vector< int >::iterator":
        return _sortinglib.IntVector_end(self)

    def rbegin(self) -> "std::vector< int >::reverse_iterator":
        return _sortinglib.IntVector_rbegin(self)

    def rend(self) -> "std::vector< int >::reverse_iterator":
        return _sortinglib.IntVector_rend(self)

    def clear(self) -> "void":
        return _sortinglib.IntVector_clear(self)

    def get_allocator(self) -> "std::vector< int >::allocator_type":
        return _sortinglib.IntVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _sortinglib.IntVector_pop_back(self)

    def erase(self, *args) -> "std::vector< int >::iterator":
        return _sortinglib.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _sortinglib.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'std::vector< int >::value_type const &') -> "void":
        return _sortinglib.IntVector_push_back(self, x)

    def front(self) -> "std::vector< int >::value_type const &":
        return _sortinglib.IntVector_front(self)

    def back(self) -> "std::vector< int >::value_type const &":
        return _sortinglib.IntVector_back(self)

    def assign(self, n: 'std::vector< int >::size_type', x: 'std::vector< int >::value_type const &') -> "void":
        return _sortinglib.IntVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _sortinglib.IntVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _sortinglib.IntVector_insert(self, *args)

    def reserve(self, n: 'std::vector< int >::size_type') -> "void":
        return _sortinglib.IntVector_reserve(self, n)

    def capacity(self) -> "std::vector< int >::size_type":
        return _sortinglib.IntVector_capacity(self)
    __swig_destroy__ = _sortinglib.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _sortinglib.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        return _sortinglib.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        return _sortinglib.DoubleVector___nonzero__(self)

    def __bool__(self) -> "bool":
        return _sortinglib.DoubleVector___bool__(self)

    def __len__(self) -> "std::vector< double >::size_type":
        return _sortinglib.DoubleVector___len__(self)

    def __getslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> "std::vector< double,std::allocator< double > > *":
        return _sortinglib.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        return _sortinglib.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i: 'std::vector< double >::difference_type', j: 'std::vector< double >::difference_type') -> "void":
        return _sortinglib.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        return _sortinglib.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< double >::value_type const &":
        return _sortinglib.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        return _sortinglib.DoubleVector___setitem__(self, *args)

    def pop(self) -> "std::vector< double >::value_type":
        return _sortinglib.DoubleVector_pop(self)

    def append(self, x: 'std::vector< double >::value_type const &') -> "void":
        return _sortinglib.DoubleVector_append(self, x)

    def empty(self) -> "bool":
        return _sortinglib.DoubleVector_empty(self)

    def size(self) -> "std::vector< double >::size_type":
        return _sortinglib.DoubleVector_size(self)

    def swap(self, v: 'DoubleVector') -> "void":
        return _sortinglib.DoubleVector_swap(self, v)

    def begin(self) -> "std::vector< double >::iterator":
        return _sortinglib.DoubleVector_begin(self)

    def end(self) -> "std::vector< double >::iterator":
        return _sortinglib.DoubleVector_end(self)

    def rbegin(self) -> "std::vector< double >::reverse_iterator":
        return _sortinglib.DoubleVector_rbegin(self)

    def rend(self) -> "std::vector< double >::reverse_iterator":
        return _sortinglib.DoubleVector_rend(self)

    def clear(self) -> "void":
        return _sortinglib.DoubleVector_clear(self)

    def get_allocator(self) -> "std::vector< double >::allocator_type":
        return _sortinglib.DoubleVector_get_allocator(self)

    def pop_back(self) -> "void":
        return _sortinglib.DoubleVector_pop_back(self)

    def erase(self, *args) -> "std::vector< double >::iterator":
        return _sortinglib.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _sortinglib.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x: 'std::vector< double >::value_type const &') -> "void":
        return _sortinglib.DoubleVector_push_back(self, x)

    def front(self) -> "std::vector< double >::value_type const &":
        return _sortinglib.DoubleVector_front(self)

    def back(self) -> "std::vector< double >::value_type const &":
        return _sortinglib.DoubleVector_back(self)

    def assign(self, n: 'std::vector< double >::size_type', x: 'std::vector< double >::value_type const &') -> "void":
        return _sortinglib.DoubleVector_assign(self, n, x)

    def resize(self, *args) -> "void":
        return _sortinglib.DoubleVector_resize(self, *args)

    def insert(self, *args) -> "void":
        return _sortinglib.DoubleVector_insert(self, *args)

    def reserve(self, n: 'std::vector< double >::size_type') -> "void":
        return _sortinglib.DoubleVector_reserve(self, n)

    def capacity(self) -> "std::vector< double >::size_type":
        return _sortinglib.DoubleVector_capacity(self)
    __swig_destroy__ = _sortinglib.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _sortinglib.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)


def rand_arr(length: 'int') -> "std::vector< double,std::allocator< double > >":
    return _sortinglib.rand_arr(length)
rand_arr = _sortinglib.rand_arr
# This file is compatible with both classic and new-style classes.


