# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Fraction')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Fraction')
    _Fraction = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Fraction', [dirname(__file__)])
        except ImportError:
            import _Fraction
            return _Fraction
        try:
            _mod = imp.load_module('_Fraction', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Fraction = swig_import_helper()
    del swig_import_helper
else:
    import _Fraction
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Fraction.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self) -> "PyObject *":
        return _Fraction.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _Fraction.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _Fraction.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _Fraction.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _Fraction.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _Fraction.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _Fraction.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _Fraction.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _Fraction.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _Fraction.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _Fraction.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _Fraction.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _Fraction.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _Fraction.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _Fraction.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _Fraction.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _Fraction.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Fraction(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Fraction, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Fraction, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _Fraction.new_Fraction(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def getNumerator(self) -> "int":
        return _Fraction.Fraction_getNumerator(self)

    def getDenominator(self) -> "int":
        return _Fraction.Fraction_getDenominator(self)

    def __add__(self, otherFrac: 'Fraction') -> "Fraction":
        return _Fraction.Fraction___add__(self, otherFrac)

    def __sub__(self, otherFrac: 'Fraction') -> "Fraction":
        return _Fraction.Fraction___sub__(self, otherFrac)

    def __mul__(self, otherFrac: 'Fraction') -> "Fraction":
        return _Fraction.Fraction___mul__(self, otherFrac)

    def __truediv__(self, *args):
        return _Fraction.Fraction___truediv__(self, *args)
    __div__ = __truediv__



    def toString(self) -> "std::string":
        return _Fraction.Fraction_toString(self)
    __swig_destroy__ = _Fraction.delete_Fraction
    __del__ = lambda self: None
Fraction_swigregister = _Fraction.Fraction_swigregister
Fraction_swigregister(Fraction)

# This file is compatible with both classic and new-style classes.


